version: '3'

networks:
  inception:
    name: inception

services:
  # wordpress:
  #   container_name: wordpress
  #   build: ./requirements/wordpress/.
  #   image: wordpress:42
  #   depends_on:
  #     - mariadb
  #   volumes:
  #     - wordpress:/var/www/html
  #   env_file:
  #     - .env
  #   networks:
  #     - inception
  #   restart: always
  nginx:
    container_name: nginx-container
    env_file:
      - .env
    depends_on:
      - mariadb
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    ports:
      - "443:443"
    restart: always

  
  mariadb:
    container_name: mariadb-container
    env_file:
      - .env
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    image: mariadb:42
    networks:
      - inception
    ports:
      - "3306:3306"
    restart: always
 

volumes:
        wordpress:
                name: wordpress
                driver: local
                driver_opts:
                        device: /home/pei/Documents/42Inception/srcs/requirements/wordpress
                        o: bind
                        type: none
